name = "Hugo Theme Vac"
license = "MIT"
licenselink = "https://github.com/tf3/hugo-theme-vac/blob/master/LICENSE"
description = ""
homepage = "https://github.com/tf3/hugo-theme-vac"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Thomas Foerster"
  homepage = "https://thomasfoerster.ca"